# Generated by Django 2.2.19 on 2023-10-24 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания записи')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения записи')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликована запись или нет')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='animals.Category')),
            ],
        ),
    ]
