# Generated by Django 4.2.6 on 2023-10-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Имя'),
        ),
    ]
